package edu.sfsu.app;

import androidx.appcompat.app.AppCompatActivity;

import android.os.Bundle;
import android.view.View;
import android.widget.Spinner;
import android.widget.TextView;

import java.util.List;

import edu.sfsu.app.Task.DataTask;

public class MainActivity extends AppCompatActivity {
    private final BeerExpert beerExpert = new BeerExpert();

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
    }

    public void onClickFindBeer(View view) {
        // R is a special Java file that gets generated by
        // Android Studio whenever you create or build your app.
        Spinner color = findViewById(R.id.beer_color);

        String beerColor = String.valueOf(color.getSelectedItem());

        TextView tv_message = findViewById(R.id.tv_main);
        tv_message.setText(String.valueOf(color.getSelectedItem()));

        // new
        List<String> brandList = beerExpert.getBrands(beerColor);

        StringBuilder brandsFormatted = new StringBuilder();

        for(String brand: brandList) {
            brandsFormatted.append(brand).append('\n');
        }

        tv_message.setText(brandsFormatted);
    }
}