package edu.sfsu.app;

import androidx.appcompat.app.AppCompatActivity;
import androidx.recyclerview.widget.RecyclerView;

import android.os.Bundle;
import android.util.Log;
import android.view.View;
import android.widget.ProgressBar;
import android.widget.Spinner;
import android.widget.TextView;

import java.util.ArrayList;
import java.util.List;

import edu.sfsu.app.Task.DataThread;
import edu.sfsu.app.model.DrinkModel;
import okhttp3.OkHttpClient;

public class MainActivity extends AppCompatActivity {
    RecyclerView recyclerView;
    ProgressBar progressBar;
    ArrayList<DrinkModel> model;
    private final BeerExpert beerExpert = new BeerExpert();

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
    }

    public void onClickFindBeer(View view) throws InterruptedException {
        // R is a special Java file that gets generated by
        // Android Studio whenever you create or build your app.
        Spinner color = findViewById(R.id.beer_color);

        String beerColor = String.valueOf(color.getSelectedItem());

        TextView tv_message = findViewById(R.id.tv_main);
        tv_message.setText(String.valueOf(color.getSelectedItem()));

        // new
        List<String> brandList = beerExpert.getBrands(beerColor);

        StringBuilder brandsFormatted = new StringBuilder();

        for(String brand: brandList) {
            brandsFormatted.append(brand).append('\n');
        }

        tv_message.setText(brandsFormatted);

        // DataTask
        recyclerView = findViewById(R.id.recyclerView);
        String api = "https://www.thecocktaildb.com/api/json/v1/1/search.php?s=margarita";
        //         new DataTask(MainActivity.this, recyclerView, progressBar, model).execute(api);
        DataThread dataThread = new DataThread(api);
        dataThread.getData(api);
        Log.v("LOG", "Main Thread");
    }
}